#!/usr/bin/env bash
set -euo pipefail

# generate-context-graph.sh
# Scans all .coao/<type>s/<slug>/relationships.md files
# and produces .coao/context-graph.md — an index of all
# cross-work-item relationships.

COAO_DIR=".coao"
OUTPUT="$COAO_DIR/context-graph.md"

cat > "$OUTPUT" << 'HEADER'
# Context Graph

Auto-generated by `generate-context-graph.sh`.
DO NOT EDIT MANUALLY. Regenerate after creating or updating relationships.md.

---

HEADER

found=0

for relfile in "$COAO_DIR"/*/*/relationships.md; do
  if [ ! -f "$relfile" ]; then
    continue
  fi

  found=$((found + 1))

  # Extract the work item path from the file path
  # .coao/<type>s/<slug>/relationships.md
  relpath="${relfile#.coao/}"
  slug="${relpath%/relationships.md}"

  echo "## $slug" >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  # Use grep/sed to parse relationships from YAML front matter
  # We extract the type and target fields from each relationship entry
  while IFS= read -r line; do
    if echo "$line" | grep -qE '^\s+-\s+type:\s+'; then
      reltype=$(echo "$line" | sed 's/.*type: *//' | sed 's/^"//; s/"$//')
    elif echo "$line" | grep -qE '^\s+target:\s+'; then
      target=$(echo "$line" | sed 's/.*target: *//' | sed 's/^"//; s/"$//')
    elif echo "$line" | grep -qE '^\s+description:\s+'; then
      desc=$(echo "$line" | sed 's/.*description: *//' | sed 's/^"//; s/"$//')
      if [ -n "${reltype:-}" ] && [ -n "${target:-}" ]; then
        # Build correct relative path from .coao/context-graph.md
        if echo "$target" | grep -qE '^(features|fixes|tasks|spikes|chores|projects|knowledge)/'; then
          # Same directory under .coao/ — link as ./target
          link="./$target"
        else
          # Repo-root path — link as ../target (strip leading ./ if present)
          link="${target#./}"
          link="../$link"
        fi
        echo "- **$reltype** → [$target]($link): $desc" >> "$OUTPUT"
      fi
      reltype=""
      target=""
    fi
  done < "$relfile"

  echo "" >> "$OUTPUT"
done

if [ "$found" -eq 0 ]; then
  echo "_No relationships defined yet._" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated on $(date '+%Y-%m-%d %H:%M:%S') | $found work item(s) with relationships." >> "$OUTPUT"

echo "context-graph.md generated: $found work item(s) indexed."
